# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ba2c414df696138b2d00de1769f7879b605e97df787f6a94c280a0cf076b2f91f1219639a933527d2db757faf866d1671445d6726e6b0f8b2db6fa9ea44c43a

test:
  secret_key_base: a1383d5fb2d542fc0f758f6a322c760c5cd7a1c446894bf06e4113081c0fa9cf2234cdfb9bbb18f1eba513c28f1dce7c20c2975ae7f5aa83fc164ebd5fb62231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
